### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by oppiet30** [damelang/precosat#1]
[oppie@dell precosat]$ make
rm -f precocfg.hh; ./mkconfig > precocfg.hh
g++ -g -Wall -Wextra -fprofile-arcs -ftest-coverage -c precomain.cc
In file included from precomain.cc:23:
precosat.hh:141:31: error: ‘ptrdiff_t’ has not been declared
  141 |   static void fix (T * & ptr, ptrdiff_t diff) {
      |                               ^~~~~~~~~
precosat.hh:247:13: error: ‘ptrdiff_t’ has not been declared
  247 |   void fix (ptrdiff_t diff) {
      |             ^~~~~~~~~
make: *** [makefile:14: precomain.o] Error 1
[oppie@dell precosat]$ 

How can I fix this?

**Comment by damelang** [comment]
I just updated this repo with the latest version (576) of the codebase (downloaded from the precosat homepage).

After applying some minor changes of my own to resolve compiler warnings, the code now compiles clean.

It looks like the precosat authors already addressed your problem years ago by simply #include'ing <cstddef> where needed.

So you just need to "git pull" and then "./configure && make", and you should be good.
